server:
  host: 127.0.0.1
  port: :3000
mysql:
  host: 127.0.0.1
  port: 3306
  config: charset=utf8mb4&parseTime=True&loc=Local
  db-name: go_react_forum
  username: root
  password: root
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: error
  log-zap: false